services:
  - type: web
    name: tasksync-portfolio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT tasksync.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tasksync-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: tasksync.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: tasksync-db
    plan: free
