# Generated by Django 6.0.1 on 2026-01-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliodocument_contactmessage_admin_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodocument',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the document'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
