# Generated by Django 6.0.1 on 2026-01-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliodocument_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(help_text='Project screenshot/thumbnail', upload_to='project_images/'),
        ),
    ]
