# Generated by Django 6.0.1 on 2026-01-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_description',
            field=models.TextField(default="Have a project in mind? I'd love to hear about it. Send me a message and let's create something amazing together."),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_social_text',
            field=models.CharField(default='Follow Me', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_title',
            field=models.CharField(default="Let's Work Together", max_length=200),
        ),
    ]
