# Generated by Django 6.0.1 on 2026-01-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_profile_bio_profile_contact_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
