# Generated by Django 6.0.1 on 2026-01-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_profile_telegram_url_profile_whatsapp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=100, help_text='Skill level 1-100'),
        ),
    ]
