# Generated by Django 6.0.1 on 2026-01-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_skill_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_greeting',
            field=models.CharField(default="Hi, I'm", max_length=100),
        ),
    ]
