# Generated by Django 6.0.1 on 2026-01-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_profile_hero_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload a custom icon image', null=True, upload_to='service_icons/'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Or provide a Google/external icon URL', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text="Icon class name (e.g., 'fas fa-globe' or Google Icon name)", max_length=50),
        ),
    ]
