# Generated by Django 6.0.1 on 2026-01-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_sitecontent_profile_about_image_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('design', 'Graphics & Design'), ('database', 'Database'), ('devops', 'DevOps'), ('mobile', 'Mobile'), ('other', 'Other')], max_length=20),
        ),
    ]
