# Generated by Django 6.0.1 on 2026-01-31 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display text (e.g., '$50 - $100')", max_length=100)),
                ('value', models.CharField(help_text="Value sent in email (e.g., '50-100')", max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='show_about',
            field=models.BooleanField(default=True, verbose_name='Show About Section'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='show_contact',
            field=models.BooleanField(default=True, verbose_name='Show Contact Section'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='show_documents',
            field=models.BooleanField(default=True, verbose_name='Show Documents Section'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='show_experience',
            field=models.BooleanField(default=True, verbose_name='Show Experience Section'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='show_hero',
            field=models.BooleanField(default=True, verbose_name='Show Hero Section'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='show_projects',
            field=models.BooleanField(default=True, verbose_name='Show Projects Section'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='show_services',
            field=models.BooleanField(default=True, verbose_name='Show Services Section'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='show_skills',
            field=models.BooleanField(default=True, verbose_name='Show Skills Section'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='show_testimonials',
            field=models.BooleanField(default=True, verbose_name='Show Testimonials Section'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory'),
        ),
    ]
